# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# for docker

spring:
  data:
    mongodb:
      uri: mongodb+srv://karinaevanglista:AQcJMpja7oKGHkmy@portfoliodb.vjiawhu.mongodb.net/?retryWrites=true&w=majority
      database: portfolio

  profiles:
    active: docker

server:
  port: 8080

